services:
  postgres:
    image: postgres:18-alpine
    container_name: backendenggo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Localpg12W1
      POSTGRES_DB: products_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backendenggo_network

volumes:
  postgres_data:
  